### ISSUE TITLE
redirect URL 

### ISSUE THREAD

**Issue by norcross** [wpsitecare/redirect-unattached-images#1]
any thought about filtering the redirect URL so people can choose where it goes?

**Comment by robneu** [comment]
That seems reasonable. I'll toss in a filter.

**Comment by norcross** [comment]
awesome.

**Comment by robneu** [comment]
Fixed in cd9231a87b758e75e154c28875f5b0bd65fbfe75

Probably a little overzealous with escaping, but eh.
